2025-04-21 02:32:29 - INFO - 开始构建UI界面
2025-04-21 02:32:29 - INFO - 初始化主窗口UI
2025-04-21 02:32:29 - INFO - 初始化扫描面板
2025-04-21 02:32:29 - INFO - 初始化频道列表
2025-04-21 02:32:29 - INFO - 频道列表模型初始化完成
2025-04-21 02:32:29 - INFO - UI界面构建完成
2025-04-21 02:32:29 - INFO - 频道列表模型初始化完成
2025-04-21 02:32:36 - INFO - 用户点击刷新EPG按钮
2025-04-21 02:32:36 - INFO - 准备启动EPG操作: update
2025-04-21 02:32:36 - INFO - [956748] 开始EPG操作: update
2025-04-21 02:32:36 - INFO - 开始下载EPG，保存路径: epg.xml
2025-04-21 02:32:36 - INFO - 合并模式: True
2025-04-21 02:32:41 - WARNING - EPG刷新失败
2025-04-21 02:32:41 - DEBUG - 尝试下载源 [https://epg.pw/xmltv/epg_CN.xml] (第1次)
2025-04-21 02:32:43 - INFO - 成功合并源 [https://epg.pw/xmltv/epg_CN.xml]
2025-04-21 02:32:48 - DEBUG - 尝试下载源 [https://epg.112114.xyz/pp.xml] (第1次)
2025-04-21 02:32:49 - INFO - 成功合并源 [https://epg.112114.xyz/pp.xml]
2025-04-21 02:32:54 - DEBUG - 尝试下载源 [http://epg.51zmt.top:8000/e.xml] (第1次)
2025-04-21 02:32:55 - INFO - 成功合并源 [http://epg.51zmt.top:8000/e.xml]
2025-04-21 02:32:55 - ERROR - 写入EPG文件失败: 'LogManager' object has no attribute 'success'
2025-04-21 02:32:55 - ERROR - [956748] EPG操作失败: EPG下载失败
2025-04-21 02:32:55 - ERROR - [956748] 详细错误信息:
Traceback (most recent call last):
  File "D:\github\IPTV-Scanner-Editor-Pro-New\epg_manager.py", line 61, in run
    result = self._update_epg(op_id)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\github\IPTV-Scanner-Editor-Pro-New\epg_manager.py", line 85, in _update_epg
    raise Exception("EPG下载失败")
Exception: EPG下载失败

